name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish Extension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: vimtor/action-zip@v1
      with:
        files: .
        recursive: true
        dest: extension_${{ github.ref_name }}.zip
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ github.ref_name }}
        path: ${{ github.workspace }}/extension_${{ github.ref_name }}.zip
    - name: Upload & Publish
      uses: mnao305/chrome-extension-upload@3.0.0
      with:
        file-path: extension_${{ github.ref_name }}.zip
        extension-id: mafijcfncjjmoajphbldbodbkefghgkd
        client-id: ${{ secrets.GOOGLE_API_CLIENT_ID }}}
        client-secret: ${{ secrets.GOOGLE_API_CLIENT_SECRET }}
        refresh-token: ${{ secrets.GOOGLE_API_REFRESH_TOKEN }}
